const CONSTANTS = {
    TAG : "tag",
    ID: "id",
    TYPE: "type",
    VARIABLES: "variables",
    NAME: "name",
    TITLE: "title",
    TEXT : "text",
    HEADER : "header",
    TRAILER: "trailer",
    POSITION: "position",
    DIRECT: "direct",
    ATTRIBUTES: "attributes",
    RESPOND: "respond",
    GROUP: "group",
    KEY: "key",
    OBJECT: "obj",
    UI_TYPE: "uiType",
    UID: "uid",
    META_DATA: "metaData",
    NAMESPACE: "namespace",
    LAZY: "lazy",
    SELF: "self",
    LOCATOR: "locator",
    EVENTS: "events",
    NO_CACHE_FOR_CHILDREN: "noCacheForChildren",
    UIOBJECT: "UiObject",
    ID_SEPARATOR: ",",
    ID_WILD_CASE: "*",
    ID_FIELD_SEPARATOR: ":",
    ALL_MATCH: "ALL",
    ROW: "ROW",
    COLUMN: "COLUMN",
    FOOTER: "FOOTER",
    TBODY: "TBODY",
    HEAD_TAG: "ht",
    BODY_TAG: "bt",
    FOOT_TAG: "ft",
    HEAD_ROW_TAG: "hrt",
    HEAD_COLUMN_TAG: "hct",
    FOOT_ROW_TAG: "frt",
    FOOT_COLUMN_TAG: "fct",
    BODY_ROW_TAG: "brt",
    BODY_COLUMN_TAG: "bct",
    SEPARATOR: "separator"

};